/* ------------------------------------------------------------------ *
 *  generate-config-migration — renders the pricing_config v3 SQL
 *  migration from src/lib/pricing-defaults.ts.
 *
 *  Usage:
 *    bun run scripts/generate-config-migration.ts           # print SQL
 *    bun run scripts/generate-config-migration.ts --write   # + write file
 *
 *  Output file: PRICING_MIGRATION_FILE (src/lib/pricing-defaults.ts) — the
 *  drift guard in pricing-defaults.test.ts reads the same constant.
 *  Deterministic by construction — no dates, no randomness — so re-running
 *  it against unchanged pricing-defaults produces a byte-identical file.
 *  Never touches any database.
 *
 *  Since 2026-09-22 the seed is authoritative: on existing rows only
 *  `sheet_units` (LIVE_WINS_KEYS in scripts/lib/config-seed.ts) survives
 *  from the live row; everything else — minimum order, sheet size, machine
 *  limits, over-limit policy, tiers — comes from the seed. Admin-form edits
 *  must be mirrored into pricing-defaults.ts (scripts/config-drift.ts).
 * ------------------------------------------------------------------ */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { writeFamilyPricing, type FamilyPricing } from "../src/lib/mdvd";
import {
  OPTIONAL_FAMILY_CONFIGS,
  PRICING_MIGRATION_FILE,
  SPEC_FAMILY_CONFIGS,
} from "../src/lib/pricing-defaults";
import { LIVE_WINS_KEYS, scalarColumns } from "./lib/config-seed";

const OUT_FILE = resolve(import.meta.dir, "..", PRICING_MIGRATION_FILE);

const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;
const slug = (s: string) => s.trim().replace(/\s+/g, "-");

function familyUpsert(family: string, cfg: FamilyPricing): string {
  const json = JSON.stringify(writeFamilyPricing(cfg));
  if (json.includes("$cfg$")) throw new Error("dollar-quote collision in config JSON");
  const scalars = scalarColumns(cfg);
  const cols = ["family", "pricing_config", ...scalars.map(([c]) => c)];
  const vals = [sqlStr(family), `$cfg$${json}$cfg$::jsonb`, ...scalars.map(([, v]) => String(v))];
  const keyArray = LIVE_WINS_KEYS.map((k) => `'${k}'`).join(",");
  const sets = [
    /* Existing rows: other top-level keys (legacy `customer`) kept; the v3
       block comes from the seed, with only the live-wins keys (sheet_units)
       layered on top. */
    `pricing_config = (COALESCE(public.families.pricing_config,'{}'::jsonb) - 'v3')
    || jsonb_build_object('v3',
         (EXCLUDED.pricing_config -> 'v3')
         || COALESCE((SELECT jsonb_object_agg(key, value)
                      FROM jsonb_each(COALESCE(public.families.pricing_config->'v3','{}'::jsonb))
                      WHERE key = ANY (ARRAY[${keyArray}])),
                     '{}'::jsonb))`,
    ...scalars.map(([c, v]) => `${c} = ${v}`),
  ];
  return [
    `INSERT INTO public.families (${cols.join(", ")})`,
    `VALUES (${vals.join(", ")})`,
    `ON CONFLICT (family) DO UPDATE SET`,
    `  ${sets.join(",\n  ")};`,
  ].join("\n");
}

function generate(): string {
  const lines: string[] = [];
  lines.push(`-- ================================================================
-- pricing_config v3 — approved family pricing configuration
--
-- GENERATED by scripts/generate-config-migration.ts from
-- src/lib/pricing-defaults.ts. Do NOT hand-edit this file — change the
-- defaults and regenerate:
--     bun run scripts/generate-config-migration.ts --write
--
-- Idempotent: safe to run more than once. Apply through Lovable (repo
-- sync) or paste into the Supabase SQL editor.
-- ================================================================

-- The pricing_config column was added out-of-band on the remote DB and
-- has no creating migration — guard every column we touch.
ALTER TABLE public.families ADD COLUMN IF NOT EXISTS pricing_config jsonb;
ALTER TABLE public.families ADD COLUMN IF NOT EXISTS cost_per_m2 numeric;
ALTER TABLE public.families ADD COLUMN IF NOT EXISTS outsource_cost_per_m2 numeric;
ALTER TABLE public.families ADD COLUMN IF NOT EXISTS outsource_width_cm numeric;
ALTER TABLE public.families ADD COLUMN IF NOT EXISTS outsource_height_cm numeric;
`);

  lines.push(`-- ----------------------------------------------------------------
-- Family configurations. On existing rows the whole v3 block comes from
-- the seed (the client's rules of 2026-09-22); only sheet_units — the
-- per-size nesting overrides entered in the app — is kept from the live
-- row, and other top-level keys of pricing_config are left untouched.
-- ----------------------------------------------------------------`);
  for (const [family, cfg] of Object.entries(SPEC_FAMILY_CONFIGS)) {
    lines.push(`\n-- ${family}`);
    lines.push(familyUpsert(family, cfg));
  }

  lines.push(`\n-- ----------------------------------------------------------------
-- NOTE: this migration touches CONFIGURATION ONLY (public.families).
-- Catalog prices in public.products are edited by hand and are never
-- written from here. Approved prices reach the engine by being marked
-- אומת in the app; SPEC_ANCHORS is kept for tests and dry-run targets.
-- ----------------------------------------------------------------`);

  lines.push(`\n-- ----------------------------------------------------------------
-- אופציונלי: מדבקה בטחונית — הסירו הערה רק באישור הלקוח
-- (optional family — uncomment only with explicit client approval)
-- ----------------------------------------------------------------`);
  for (const [family, cfg] of Object.entries(OPTIONAL_FAMILY_CONFIGS)) {
    const commented = familyUpsert(family, cfg)
      .split("\n")
      .map((l) => `-- ${l}`)
      .join("\n");
    lines.push(`\n-- ${family}`);
    lines.push(commented);
  }

  return lines.join("\n") + "\n";
}

const sql = generate();
console.log(sql);
if (process.argv.includes("--write")) {
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, sql, "utf8");
  console.error(`written: ${OUT_FILE}`);
}
